#!/bin/bash

rm -rf ./config-files
mkdir config-files

cp ~/.config/nvim/init.vim config-files
cp ~/.config/nvim/coc-settings.json config-files
cp -r ~/.config/coc/ultisnips config-files

cp ~/.zshrc config-files
cp ~/.tmux.conf config-files
cp ~/.ideavimrc config-files
cp ~/.Xmodmap config-files
cp ~/.imwheelrc config-files

dconf dump /org/gnome/terminal/legacy/profiles:/ > ./config-files/profiles.dconf
# backup terminal profiles command
# dconf dump /org/gnome/terminal/legacy/profiles:/:1430663d-083b-4737-a7f5-8378cc8226d1/ < ./config-files/profiles.dconf

echo "**** Backup config files success ****"

# cp ~/{.zshrc,.tmux.conf,.ideavimrc,.Xmodmap,.imwheelrc} config-files
