#!/bin/bash

echo "migrating config files..."

if [ ! -d "${HOME}/.config" ]; then
    mkdir ${HOME}/.config
    if [ ! -d "${HOME}/.config/nvim" ]; then
        mkdir ${HOME}/.config/nvim
    fi
fi

if [ ! -d "${HOME}/.config/coc" ]; then
    mkdir ${HOME}/.config/coc
fi

cp ./config-files/init.vim ${HOME}/.config/nvim
cp ./config-files/coc-settings.json ${HOME}/.config/nvim

cp ./config-files/{.ideavimrc,.imwheelrc,.zshrc,.tmux.conf,.Xmodmap} ${HOME}

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo "migratting completed"
